"""update_schema_v2

Revision ID: 5f95f41cee00
Revises: 9a502ab17128
Create Date: 2025-12-04 15:01:04.491044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f95f41cee00'
down_revision = '9a502ab17128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_tokens_email'), 'invitation_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_invitation_tokens_token'), 'invitation_tokens', ['token'], unique=True)
    op.create_table('nearby_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('properties', sa.Column('short_title', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('recommended_days', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('recommended_nights', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('min_nights', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('max_nights', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('min_guests', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('max_guests', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('properties', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('properties', sa.Column('city', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('state', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('registration_status', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('registration_submitted_by', sa.UUID(), nullable=True))
    op.add_column('properties', sa.Column('registration_submitted_at', sa.Date(), nullable=True))
    op.add_column('properties', sa.Column('property_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('properties', 'map_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'properties', 'users', ['registration_submitted_by'], ['id'], ondelete='SET NULL')
    op.drop_column('properties', 'meta')
    op.drop_column('properties', 'guest_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('guest_range', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.alter_column('properties', 'map_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('properties', 'property_meta')
    op.drop_column('properties', 'registration_submitted_at')
    op.drop_column('properties', 'registration_submitted_by')
    op.drop_column('properties', 'registration_status')
    op.drop_column('properties', 'reviews_count')
    op.drop_column('properties', 'website_url')
    op.drop_column('properties', 'postal_code')
    op.drop_column('properties', 'state')
    op.drop_column('properties', 'city')
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    op.drop_column('properties', 'about')
    op.drop_column('properties', 'max_guests')
    op.drop_column('properties', 'min_guests')
    op.drop_column('properties', 'max_nights')
    op.drop_column('properties', 'min_nights')
    op.drop_column('properties', 'recommended_nights')
    op.drop_column('properties', 'recommended_days')
    op.drop_column('properties', 'short_title')
    op.drop_table('nearby_places')
    op.drop_index(op.f('ix_invitation_tokens_token'), table_name='invitation_tokens')
    op.drop_index(op.f('ix_invitation_tokens_email'), table_name='invitation_tokens')
    op.drop_table('invitation_tokens')
    # ### end Alembic commands ###
