"""properties schema migration

Revision ID: 862c78ea080b
Revises: dfd0c4df9111
Create Date: 2025-12-05 13:28:13.305680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862c78ea080b'
down_revision = 'dfd0c4df9111'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
