"""recreate migration

Revision ID: 90950b704b65
Revises: 9a502ab17128
Create Date: 2025-12-03 14:41:41.179598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90950b704b65'
down_revision = '9a502ab17128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
