"""add_duration_to_logs

Revision ID: b07d9d9deca7
Revises: ceee39e94849
Create Date: 2025-11-28 13:13:57.247394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07d9d9deca7'
down_revision = 'ceee39e94849'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'duration')
    # ### end Alembic commands ###
